version = 1

[[annotations]]
path = "**"
precedence = "closest"
SPDX-FileCopyrightText = "2026 ForestMate contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "packaging/android/app/build.gradle",
  "packaging/android/app/src/main/AndroidManifest.xml",
  "packaging/android/app/src/main/java/kr/forestmate/app/Application.java",
  "packaging/android/app/src/main/java/kr/forestmate/app/LauncherActivity.java",
  "packaging/android/app/src/main/res/drawable-anydpi/shortcut_legacy_background.xml",
  "packaging/android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml",
  "packaging/android/app/src/main/res/values/colors.xml",
  "packaging/android/app/src/main/res/values/strings.xml",
  "packaging/android/app/src/main/res/xml/filepaths.xml",
  "packaging/android/build.gradle",
]
precedence = "override"
SPDX-FileCopyrightText = "2019-2021 Google Inc."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "packaging/android/gradle/wrapper/**",
  "packaging/android/gradlew",
  "packaging/android/gradlew.bat",
]
precedence = "override"
SPDX-FileCopyrightText = "2015-2021 the original authors"
SPDX-License-Identifier = "Apache-2.0"
