package kr.forestmate.app

import kr.forestmate.core.model.Course
import kr.forestmate.core.model.Hazard

object LocalCatalog {
    val courses: List<Course> = listOf(
        Course(
            id = "bukhansan",
            name = "북한산 백운대 코스",
            km = 4.2,
            minutes = 190,
            route = "백운대탐방지원센터 → 백운대 정상",
            hazards = listOf(
                Hazard(type = "낙석주의", grade = "산사태 1등급", at = 0.62, note = "최근 2주 강우 누적 — 우회로 권장"),
                Hazard(type = "급경사", grade = "사고다발 구간", at = 0.38, note = "스틱 사용·심박 주의"),
            ),
            level = "중",
            levelN = 2,
            crowd = "보통",
            view = 4,
            peak = "백운대 836m",
            gridNo = "다사 5683 2741",
            gps = "37.6584,126.9778",
            rescuePoint = "백운산장 헬기장 620m",
            fireStation = "서울 종로소방서 산악구조대",
            elevation = listOf(120, 180, 260, 390, 480, 542, 650, 770, 836),
        ),
        Course(
            id = "inwangsan",
            name = "인왕산 자락길 둘레",
            km = 2.8,
            minutes = 100,
            route = "사직공원 → 수성동계곡",
            hazards = listOf(Hazard(type = "혼잡구간", grade = "주말 정체", at = 0.55, note = "성곽길 합류 — 추월 자제")),
            level = "하",
            levelN = 1,
            crowd = "낮음",
            view = 3,
            peak = "인왕산 338m",
            gridNo = "다사 5421 2856",
            gps = "37.5772,126.9610",
            rescuePoint = "황학정 진입로 280m",
            fireStation = "서울 종로소방서",
            elevation = listOf(60, 95, 140, 180, 210, 196, 170, 150, 130),
        ),
        Course(
            id = "achasan",
            name = "아차산 해맞이 능선",
            km = 3.5,
            minutes = 140,
            route = "아차산생태공원 → 해맞이광장",
            hazards = listOf(Hazard(type = "암릉구간", grade = "주의", at = 0.70, note = "우천 시 미끄럼 — 난간 이용")),
            level = "하",
            levelN = 1,
            crowd = "보통",
            view = 5,
            peak = "아차산 287m",
            gridNo = "마바 1043 1822",
            gps = "37.5713,127.1030",
            rescuePoint = "해맞이광장 헬기포인트",
            fireStation = "구리소방서",
            elevation = listOf(40, 80, 130, 170, 210, 240, 262, 280, 287),
        ),
        Course(
            id = "dobong",
            name = "도봉산 신선대 코스",
            km = 6.4,
            minutes = 280,
            route = "도봉탐방지원센터 → 신선대",
            hazards = listOf(
                Hazard(type = "Y계곡 암릉", grade = "사고다발", at = 0.78, note = "강풍 시 우회 권장"),
                Hazard(type = "낙석주의", grade = "산사태 2등급", at = 0.45, note = "헬멧 권장 구간"),
            ),
            level = "상",
            levelN = 3,
            crowd = "높음",
            view = 5,
            peak = "신선대 726m",
            gridNo = "다사 6122 3354",
            gps = "37.6987,127.0114",
            rescuePoint = "도봉대피소 410m",
            fireStation = "도봉소방서 산악구조대",
            elevation = listOf(110, 190, 300, 420, 510, 600, 660, 700, 726),
        ),
    )
}
